Fixed AngleDiff and AngleDist function definitions and added unit tests.
ut-amrl/amrl_shared_lib pull request #4
Opened 2020-06-03 17:59 UTC by kylevedder

2020-06-03 18:11 UTC, joydeep-b requested changes
Thanks for the contributions, @kylevedder .
I separately made this change on my end to be auto-diff friendly, but it would be good to have it in the main library.
Two main changes needed:
1. Please use `atan2`, not `acos`.
2. Please add in the template specializations for `float` and `double` using `rint` instead of the trig functions: it will be **much** faster for them.

2020-06-03 18:11 UTC, joydeep-b commented on math/geometry.h
> +  const auto angle = std::acos(h1.dot(h2));
Please use `atan2`, not acos. The co-domain of acos is not the full -pi to pi.

2020-06-03 18:11 UTC, joydeep-b commented on math/geometry.h
> +  const auto angle = std::acos(h1.dot(h2));
Please use `atan2`, not acos. The co-domain of acos is not the full -pi to pi.

2020-06-03 18:11 UTC, joydeep-b commented on math/geometry.h
> +  const int sign = math_util::Sign(Cross(h1, h2));
You won't need to do this with `atan2`.

2020-06-03 19:06 UTC, kylevedder commented
1. Every `atan2` based approach I can think of has numerical stability problems (e.g. when the two angles are the same) and I don't see why it'd be any faster. What was the exact mathematical formula you were looking for? I also don't understand the concern over `acos`'s co-domain. `AngleDist(a, b)` measures the unsigned distance between `a` and `b` which will fall from `0` to `pi`, so the naked use of `acos` is fine. `AngleDiff` measure the signed distance between `a` and `b` which will fall from `-pi` to `pi`, but the sign computation takes care of negating the `acos`'s output properly so it will on the full range from `-pi` to `pi`.

2. I don't understand what you are looking for with the template specializations for `float` and `double` using `rint` specializations; `rint` rounds floating point numbers to integral values but I don't understand why that's relevant to these functions.

2020-06-05 13:26 UTC, joydeep-b commented
@kylevedder 
There seem to be a number of differences in how you expect these functions to work, and how we do. Let's talk on Zoom to go over them, it'll be faster.

2020-06-05 14:55 UTC, joydeep-b commented
Correct AngleDiff implementation:

```cpp
template <typename T>
T AngleDiff(T a0, T a1) {
  const T s = std::sin(a0 - a1);
  const T c = std::cos(a0 - a1);
  return std::atan2(s, c);
}
```

2020-06-05 15:38 UTC, kylevedder commented
I have moved the functions back to `math_util`, added a generic version that uses trig functions along with template specialization for `float` and `double`, and added tests which check the generic trig version, the template specialization of `float`, and the template specialization of `double`.

2020-06-05 15:50 UTC, joydeep-b requested changes
One small change needed.

2020-06-05 15:50 UTC, joydeep-b commented on math/math_util.h
>  T AngleDiff(T a0, T a1) {
This should be `const T&`.

2020-06-05 16:40 UTC, kylevedder commented on math/math_util.h
>  T AngleDiff(T a0, T a1) {
Fixed this and all other relevant functions.

2020-06-05 16:49 UTC, joydeep-b approved these changes
LGTM. Please merge when ready.

2020-06-05 16:49 UTC, merged